--- #YAML:1.0
name:               Term-GentooFunctions
version:            1.3
abstract:           ~
author:  []
license:            LGPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:              5.006001
    Term::ANSIColor:   0
    Term::ANSIScreen:  0
    Term::Size:        0
resources:
    repository:  http://github.com/jettero/term--gentoofunctions
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - einfo
    - ebegin
    - eend
