--- #YAML:1.0
name:                Term-GentooFunctions
version:             1.01.4
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Term::ANSIColor:               0
    Term::ANSIScreen:              0
    Term::Size:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
