# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-GentooFunctions
version:      0.99
version_from: Term/GentooFunctions.pm
installdirs:  site
requires:
    Term::ANSIColor:               0
    Term::ANSIScreen:              0
    Term::Size:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
